<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Benajamin Ojeda y Miguel Tognarelli">

<title>Trabajo 1: Reporte descriptivo en Quarto; Trabajo 2: Asociación de variables y contrucción de indices/escalas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Preparación_files/libs/clipboard/clipboard.min.js"></script>
<script src="Preparación_files/libs/quarto-html/quarto.js"></script>
<script src="Preparación_files/libs/quarto-html/popper.min.js"></script>
<script src="Preparación_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Preparación_files/libs/quarto-html/anchor.min.js"></script>
<link href="Preparación_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Preparación_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Preparación_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Preparación_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Preparación_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Preparación_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Preparación_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo 1: Reporte descriptivo en Quarto; Trabajo 2: Asociación de variables y contrucción de indices/escalas</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Benajamin Ojeda y Miguel Tognarelli </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="trabajo-1" class="level1">
<h1>Trabajo 1:</h1>
</section>
<section id="determinantes-residenciales-que-motivan-la-decision-del-cambio-de-hogar-en-chile" class="level1">
<h1>Determinantes residenciales que motivan la decision del cambio de hogar en Chile</h1>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">1. Introducción</h2>
<p>La satisfacción residencial se entiende como un componente clave y muy influyentes en como las personas experimentan y valoran su entorno inmediato, esta satisfacción no se construye de forma aislada si no que es en un tramado de elementos físicos-materiales y sociales, “Es un concepto multi dimensional, ya que incluye factores físicos, sociales y vecinales” (Martínez Ibarra &amp; Ibarra Salazar, 2017).&nbsp;</p>
<p>Cuando hablamos de elementos físicos-materiales que poseen los entornos residenciales, nos referimos a aspectos como la presencia de áreas verde, la conectividad, la limpieza del espacio público, entre otros factores materiales, centrarse únicamente en estas dimensiones no nos permitiría comprender de forma completa la experiencia residencial es por eso que consideramos muy importante tener en cuenta aquellos aspectos sociales como la identificación al barrio, las relaciones con los individuos, la percepción de seguridad, entre otros. La sociología urbana ha señalado como la insatisfacción con el entorno residencial puede reflejar tensiones vinculadas a la exclusión social, la percepción de seguridad o la baja calidad de servicios urbanos (Sabatini,2009)&nbsp;</p>
<p>El estudiar&nbsp;las determinantes que conllevarían a un cambio de hogar nos demuestra cómo se expresan fenómenos que van más allá de un cambio de hogar, entenderemos como determinantes de satisfacción&nbsp;a partir de los siguientes 4 aspectos planteado por los autores mexicanos a partir de la encuesta de satisfacción residencial: la satisfacción depende de cuatro características: 1) físicas de la construcción, 2) espaciales, funcionales y formales, 3) ambientales, y 4) adaptaciones y transformaciones (Martínez Ibarra &amp; Ibarra Salazar, 2017). La decisión de cambiar de vivienda no es solo un hecho individual, sino que también es una respuesta a ciertas condiciones estructurales que alteran los modos de vida y las rutinas de las personas.&nbsp;Además, es fundamental no dejar de lado el contexto chileno, en donde el acceso a la vivienda se encuentra altamente mercantilizado, estos elevados costos presentan una barrera significativa, sobre todo para el sector de los bajos recursos, que condiciona las posibilidades de elección y movilidad residencial&nbsp;</p>
<p>El concepto central que se va a investigar es la satisfacción residencial, en donde la entenderemos como una evaluación subjetiva que realiza el individuo sobre sus condiciones de su vivienda y el entorno inmediato en el cual se encuentra, tanto en lo social como en lo físico, se tendrá por objetivo estudiar cómo es que esta satisfacción generada por estas condiciones&nbsp;incide en la decisión de un cambio de hogar. Tal y como señala (Amérigo, <em>et al</em>, 2014) la satisfacción residencial no depende únicamente de la calidad objetiva de la vivienda, sino también de factores subjetivos, como la percepción del entorno y el grado de apego o identidad con el lugar&nbsp;</p>
<section id="hipotesis" class="level3">
<h3 class="anchored" data-anchor-id="hipotesis">1.1 Hipotesis</h3>
<p>La hipótesis central que plantearemos es que se espera que a medida que disminuya la satisfacción residencial tanto en sus aspectos físicos y sociales, aumente la probabilidad que una persona decida cambiarse de hogar. esta relación parte del supuesto que el grado que la persona se siente satisfecha tanto en lo físico-material como en lo social, actúan como indicadores claves en la influencia sobre la decisión que tengan las personas a querer cambiarse de hogar.&nbsp;</p>
</section>
</section>
<section id="preparación" class="level2">
<h2 class="anchored" data-anchor-id="preparación">2. Preparación</h2>
<section id="instalación-de-paquetes" class="level3">
<h3 class="anchored" data-anchor-id="instalación-de-paquetes">2.1. Instalación de paquetes:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               dplyr,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>              stargazer, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>              sjmisc, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>              summarytools, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>              kableExtra, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>              sjPlot,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>              corrplot, </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>              sessioninfo, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>              ggplot2,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>              knitr) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="descarga-de-la-base-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="descarga-de-la-base-de-datos">2.2 Descarga de la base de datos</h3>
<p>Nuestra base de datos con la que nos dispondriamos a trabajar seria la “Encuesta Longitudinal Social de Chile” realizada por el COES (Centro de Estudios de Conflicto y Cohesión social).</p>
<p>Y esta base la descargamos desde internet con el siguiente link:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://dataverse.harvard.edu/api/access/datafile/7245118"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploración-de-la-base-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="exploración-de-la-base-de-datos">2.3 Exploración de la base de datos</h3>
<p>Esto lo realizamos con el fin de saber las dimensiones de la base de datos en cuanto a el numero de observaciones que esta tendria y el numero de variables de las que dispondria.</p>
<p>Para aquello aplicamos el siguiente codigo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(elsoc_long_2016_2022<span class="fl">.2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18035   750</code></pre>
</div>
</div>
<p>Podemos apreciar que la base de datos cuenta con un total de 18035 observaciones que fueron realizadas desde el año 2016 al año 2022 y un total de 750 variables.</p>
</section>
<section id="seleccion-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="seleccion-de-variables">2.4 Seleccion de variables</h3>
<p>Para seleccionar nuestras variables utilizaremos el comando find_var, este comando nos permitiria localizar variables en la base de datos a partir de una palabra que sea de nuestro interes.</p>
<p>Dichas palabras que utilizaremos seria: barrio y satisfacción.</p>
<p>Palabra “Satisfaccion”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> elsoc_long_2016_2022<span class="fl">.2</span>, <span class="st">"satisfaccion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   col.nr var.name
1     159   t06_01
2     160   t06_02
3     161   t06_03
4     162   t06_04
5     163   t06_05
6     164   t06_06
7     165   t06_07
8     166   t06_08
9     167   t07_01
10    168   t07_02
11    395   d27_01
12    397   d27_03
                                                               var.label
1                            Grado de satisfaccion: Seguridad del barrio
2                                    Grado de satisfaccion: Conectividad
3       Grado de satisfaccion:  Areas verdes y de recreacion disponibles
4                   Grado de satisfaccion: Limpieza y belleza del barrio
5      Grado de satisfaccion: Proximidad al lugar de actividad principal
6         Grado de satisfaccion:  Proximidad a colegios de buena calidad
7                 Grado de satisfaccion:  Proximidad a areas de comercio
8  Grado de satisfaccion:  Proximidad con familiares y/o amigos cercanos
9                         Grado de satisfaccion: Tamannio de la vivienda
10                         Grado de satisfaccion: Calidad de la vivienda
11      Grado de acuerdo: Insatisfaccion al compararme con otros como yo
12   Grado de acuerdo: Insatisfaccion al compararme con clases mas altas</code></pre>
</div>
</div>
<p>Palabra “Barrio”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> elsoc_long_2016_2022<span class="fl">.2</span>,<span class="st">"barrio"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   col.nr      var.name
1      90 r13_barrio_01
2     100 r13_barrio_02
3     110 r13_barrio_03
4     120 r13_barrio_04
5     130 r13_barrio_05
6     143        t02_01
7     144        t02_02
8     145        t02_03
9     146        t02_04
10    147        t03_01
11    148        t03_02
12    149        t03_03
13    150        t03_04
14    151        t04_01
15    152        t04_02
16    155        t04_05
17    156        t04_06
18    157        t04_07
19    159        t06_01
20    162        t06_04
21    169           t08
22    173           t10
23    176        t11_03
24    183           t15
25    184           t16
26    185           t17
27    382        d24_02
28    595        m34_03
                                                                  var.label
1                                            Confidente 1: Mismo vecindario
2                                            Confidente 2: Mismo vecindario
3                                            Confidente 3: Mismo vecindario
4                                            Confidente 4: Mismo vecindario
5                                            Confidente 5: Mismo vecindario
6                         Grado de acuerdo: Este es el barrio ideal para mi
7                    Grado de acuerdo: Me siento integrado/a en este barrio
8               Grado de acuerdo: Me identifico con la gente de este barrio
9                              Grado de acuerdo: Este barrio es parte de mi
10                   Grado de acuerdo: En este barrio es facil hacer amigos
11                    Grado de acuerdo: La gente en este barrio es sociable
12                     Grado de acuerdo: La gente en este barrio es cordial
13                Grado de acuerdo: La gente en este barrio es colaboradora
14              Grado de acuerdo: Me agrada el cambio en aspecto del barrio
15     Grado de acuerdo:  Encarecimiento de bienes y servicios en el barrio
16             Grado de acuerdo:  Abandono de vecinos y/o amigos del barrio
17         Grado de acuerdo:  Llegada de residentes desagradables al barrio
18 Grado de acuerdo:  Surgimiento de actividades desagradables en el barrio
19                              Grado de satisfaccion: Seguridad del barrio
20                     Grado de satisfaccion: Limpieza y belleza del barrio
21                                      Percepcion de evaluacion del barrio
22                                       Percepcion de seguridad del barrio
23           Frecuencia: Amenazas, insultos u ofensas de vecinos del barrio
24                             Nivel de dannio que ha ocurrido en su barrio
25         Justificacion de violencia: Personas dannien bienes en su barrio
26     Justificacion de violencia: Personas dannien bienes en otros barrios
27 Grado de acuerdo: Poderosos indolentes con problemas graves en mi barrio
28                                              Tiempo residiendo en barrio</code></pre>
</div>
</div>
<p>A partir de estas palabras podemos seleccionar que variables utilizar y tambien a partir de estas variables tambien podemos hacernos una idea de en que modulo podrian haber variables similares de nuestro interes en caso de querer localizarlas/emplearlas.</p>
</section>
<section id="creacion-de-una-sub-base-con-nuestras-variables-de-interes" class="level3">
<h3 class="anchored" data-anchor-id="creacion-de-una-sub-base-con-nuestras-variables-de-interes">2.5 Creacion de una sub-base con nuestras variables de interes</h3>
<p>Algunas de estas variables se obtivieron a partir del uso del comando find:var, las otras fueron buscadas de forma manual el el logro de codigos utilizando de referencia las variables obtenidas por find_var.</p>
<p>Esta sub-base contempla la selección de las observaciones correspondientes a la Ola 6 que seria los datos del año 2022.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022 <span class="ot">&lt;-</span> elsoc_long_2016_2022<span class="fl">.2</span> <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ola<span class="sc">==</span><span class="st">"6"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">Barrio_ideal=</span>t02_01,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Integra_barrio=</span>t02_02,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Identi_gente=</span>t02_03, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Parte_barrio=</span>t02_04,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">Cambio_hogar=</span>t05,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_seguridad=</span>t06_01,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_conectividad=</span>t06_02,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_area_ocio=</span>t06_03,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_barrio_limp=</span>t06_04,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_cerca_trab=</span>t06_05,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_cerca_coleg=</span>t06_06,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_cerca_comerc=</span>t06_07,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_cerca_amig_fami=</span>t06_08,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_tamano_viv=</span>t07_01,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">Satis_calidad_viv=</span>t07_02,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">Frecue_peleas_calle=</span>t09_01,</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">Frecue_robo=</span>t09_02,</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">Frecue_trafico=</span>t09_03,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">Frecue_ruido_moles=</span>t11_01,</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">Frecue_amenzas=</span>t11_03,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">Frecue_vecino_sucio=</span>t11_04</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="tratamiento-de-los-casos-perdidos" class="level4">
<h4 class="anchored" data-anchor-id="tratamiento-de-los-casos-perdidos">2.5.1 Tratamiento de los casos perdidos</h4>
<p>Eliminamos los datos perdidos correspondientes a NS/NR (No sabe/No responde) y que estan numeradas como -999, -888 y -777 con el siguiente codigo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022 <span class="ot">&lt;-</span> proc_data_2022 <span class="sc">%&gt;%</span> sjlabelled<span class="sc">::</span><span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">777</span>, <span class="sc">-</span><span class="dv">666</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Con el codigo anterior aquellos valores de -999, -888 y -777 pasaran a ser designados como NA’s</p>
</section>
<section id="guardamos-de-la-sub-base-de-datos-realizada" class="level4">
<h4 class="anchored" data-anchor-id="guardamos-de-la-sub-base-de-datos-realizada">2.5.2 Guardamos de la sub-base de datos realizada</h4>
<p>Esta base de datos pasaria a estar alojada en la carpeta denominada imput</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_data_2022, <span class="at">file =</span> <span class="st">"C:/Users/jmuno/OneDrive/Desktop/OFC_R/Ojeda-Tognarelli-Trabajo-1/imput/proc_data_2022.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="asignación-de-etiquetas-a-las-variables" class="level2">
<h2 class="anchored" data-anchor-id="asignación-de-etiquetas-a-las-variables">2.6 Asignación de etiquetas a las variables</h2>
<p>asigamos etiquetas a cada una de las variables que disponga la sub-base que hemos realizado, con estas etiquetas asignadas se facilitaria su identificación para futuros ejercicios.</p>
<p>De momento estas etiquetas constarian en su primera parte de una breve descripción de aquello que busca medir y en la segunda parte de una breve descripcion del contenido de la pregunta</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Barrio_ideal <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Barrio_ideal,<span class="at">label =</span> <span class="st">"Grado de acuerdo: Pertinencia barrio"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Integra_barrio <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Integra_barrio,<span class="at">label =</span> <span class="st">"Grado de acuerdo: Integracion barrio"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Identi_gente <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Identi_gente,<span class="at">label =</span> <span class="st">"Grado de acuerdo: Identifica con gente del barrio"</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Parte_barrio <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Parte_barrio,<span class="at">label =</span> <span class="st">"Grado de acuerdo: Forma parte del barrio"</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Cambio_hogar <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Cambio_hogar,<span class="at">label =</span> <span class="st">"Tiene planteado cambio de casa u hogar"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_seguridad <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_seguridad,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Seguridad del barrio barrio"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_area_ocio <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_area_ocio,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Cercania a areas verdes o lugares de ocio"</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_barrio_limp <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_barrio_limp,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Limpieza o belleza del barrio"</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_cerca_trab <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_cerca_trab,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Cercania al lugar de trabajo o actividad pricipal"</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_cerca_coleg <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_cerca_coleg,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Proximidad o cercania a colegios de calidad"</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_cerca_comerc <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_cerca_comerc,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Cercania a lugares de comercio"</span>)</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_cerca_amig_fami <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_cerca_amig_fami,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Cercania con amigos/familiares"</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_tamano_viv <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_tamano_viv,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Tamano de la vivienda"</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Satis_calidad_viv <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Satis_tamano_viv,<span class="at">label =</span> <span class="st">"Grado de satisfaccion: Calidad de la vivienda"</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Frecue_peleas_calle <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Frecue_peleas_calle,<span class="at">label =</span> <span class="st">"Frecuencia: Rinas o peleas callejeras"</span>)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Frecue_robo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Frecue_robo,<span class="at">label =</span> <span class="st">"Frecuencia: Robos o asaltos"</span>)</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Frecue_trafico <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Frecue_trafico,<span class="at">label =</span> <span class="st">"Frecuencia: Trafico de drogas"</span>)</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Frecue_ruido_moles <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Frecue_ruido_moles,<span class="at">label =</span> <span class="st">"Frecuencia: Ruidos molestos"</span>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Frecue_amenzas <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Frecue_amenzas,<span class="at">label =</span> <span class="st">"Frecuencia: Amenazas de vecinos"</span>)</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>proc_data_2022<span class="sc">$</span>Frecue_vecino_sucio <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022<span class="sc">$</span>Frecue_vecino_sucio,<span class="at">label =</span> <span class="st">"Frecuencia: problemas con vecinos para botar la basura"</span>)</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Barrio_ideal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de acuerdo: Pertinencia barrio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Integra_barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de acuerdo: Integracion barrio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Identi_gente)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de acuerdo: Identifica con gente del barrio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Parte_barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de acuerdo: Forma parte del barrio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Cambio_hogar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tiene planteado cambio de casa u hogar"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_seguridad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Seguridad del barrio barrio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_conectividad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Conectividad"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_area_ocio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Cercania a areas verdes o lugares de ocio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_barrio_limp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Limpieza o belleza del barrio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_cerca_trab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Cercania al lugar de trabajo o actividad pricipal"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_cerca_coleg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Proximidad o cercania a colegios de calidad"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_cerca_comerc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Cercania a lugares de comercio"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_cerca_amig_fami)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Cercania con amigos/familiares"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_tamano_viv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Tamano de la vivienda"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Satis_calidad_viv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grado de satisfaccion: Calidad de la vivienda"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Frecue_peleas_calle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Frecuencia: Rinas o peleas callejeras"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Frecue_robo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Frecuencia: Robos o asaltos"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Frecue_trafico)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Frecuencia: Trafico de drogas"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Frecue_ruido_moles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Frecuencia: Ruidos molestos"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Frecue_amenzas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Frecuencia: Amenazas de vecinos"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022<span class="sc">$</span>Frecue_vecino_sucio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Frecuencia: problemas con vecinos para botar la basura"</code></pre>
</div>
</div>
</section>
</section>
<section id="analisis-de-tabla-y-graficos" class="level1">
<h1>3. Analisis de tabla y graficos</h1>
<section id="analisis-de-la-tabla-descriptivo-de-las-medidas-de-tendencia-central-de-las-variables." class="level2">
<h2 class="anchored" data-anchor-id="analisis-de-la-tabla-descriptivo-de-las-medidas-de-tendencia-central-de-las-variables.">3.1 Analisis de la tabla descriptivo de las medidas de tendencia central de las variables.</h2>
<p>Esta tabla cuenta con los siguientes estadisticos:</p>
<ul>
<li><p>Descriptivos generales: La pregunta realizada (label), Numero de N’s (n) y la proporción de NA’s (NA.proc)</p></li>
<li><p>Medidas de tendencia central tales como la: Media (mean) y el Rango (range) el cual este ultimo aportaria con los valores minimos y maximos</p></li>
<li><p>Medidas de disperción como: la desviación estandar (sd)</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data_2022,</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>))<span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable</span>(.,<span class="st">"markdown"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable_styling</span>(<span class="at">full_width =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scroll_box</span>(<span class="at">width =</span> <span class="st">"175%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:175%; ">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">var</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">label</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NA.prc</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Barrio_ideal</td>
<td style="text-align: left;">Grado de acuerdo: Pertinencia barrio</td>
<td style="text-align: right;">2572</td>
<td style="text-align: right;">5.787546</td>
<td style="text-align: right;">3.680404</td>
<td style="text-align: right;">0.9708494</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">Integra_barrio</td>
<td style="text-align: left;">Grado de acuerdo: Integracion barrio</td>
<td style="text-align: right;">2572</td>
<td style="text-align: right;">5.787546</td>
<td style="text-align: right;">3.729782</td>
<td style="text-align: right;">0.9130198</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">Identi_gente</td>
<td style="text-align: left;">Grado de acuerdo: Identifica con gente del barrio</td>
<td style="text-align: right;">2570</td>
<td style="text-align: right;">5.860806</td>
<td style="text-align: right;">3.635798</td>
<td style="text-align: right;">0.9582785</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">Parte_barrio</td>
<td style="text-align: left;">Grado de acuerdo: Forma parte del barrio</td>
<td style="text-align: right;">2570</td>
<td style="text-align: right;">5.860806</td>
<td style="text-align: right;">3.724903</td>
<td style="text-align: right;">0.9297024</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Cambio_hogar</td>
<td style="text-align: left;">Tiene planteado cambio de casa u hogar</td>
<td style="text-align: right;">2536</td>
<td style="text-align: right;">7.106227</td>
<td style="text-align: right;">2.933754</td>
<td style="text-align: right;">0.8673046</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">Satis_seguridad</td>
<td style="text-align: left;">Grado de satisfaccion: Seguridad del barrio barrio</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">5.824176</td>
<td style="text-align: right;">3.279658</td>
<td style="text-align: right;">1.0662721</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">Satis_conectividad</td>
<td style="text-align: left;">Grado de satisfaccion: Conectividad</td>
<td style="text-align: right;">2567</td>
<td style="text-align: right;">5.970696</td>
<td style="text-align: right;">3.688742</td>
<td style="text-align: right;">0.9811760</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">Satis_area_ocio</td>
<td style="text-align: left;">Grado de satisfaccion: Cercania a areas verdes o lugares de ocio</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">5.824176</td>
<td style="text-align: right;">3.243485</td>
<td style="text-align: right;">1.1073821</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">Satis_barrio_limp</td>
<td style="text-align: left;">Grado de satisfaccion: Limpieza o belleza del barrio</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">5.824176</td>
<td style="text-align: right;">3.253598</td>
<td style="text-align: right;">1.0502277</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">Satis_cerca_trab</td>
<td style="text-align: left;">Grado de satisfaccion: Cercania al lugar de trabajo o actividad pricipal</td>
<td style="text-align: right;">2546</td>
<td style="text-align: right;">6.739927</td>
<td style="text-align: right;">3.576983</td>
<td style="text-align: right;">0.9608058</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16</td>
<td style="text-align: left;">Satis_cerca_coleg</td>
<td style="text-align: left;">Grado de satisfaccion: Proximidad o cercania a colegios de calidad</td>
<td style="text-align: right;">2554</td>
<td style="text-align: right;">6.446886</td>
<td style="text-align: right;">3.742365</td>
<td style="text-align: right;">0.8798738</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">17</td>
<td style="text-align: left;">Satis_cerca_comerc</td>
<td style="text-align: left;">Grado de satisfaccion: Cercania a lugares de comercio</td>
<td style="text-align: right;">2570</td>
<td style="text-align: right;">5.860806</td>
<td style="text-align: right;">3.767704</td>
<td style="text-align: right;">0.9024683</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">Satis_cerca_amig_fami</td>
<td style="text-align: left;">Grado de satisfaccion: Cercania con amigos/familiares</td>
<td style="text-align: right;">2570</td>
<td style="text-align: right;">5.860806</td>
<td style="text-align: right;">3.608560</td>
<td style="text-align: right;">0.9552485</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">21</td>
<td style="text-align: left;">Satis_tamano_viv</td>
<td style="text-align: left;">Grado de satisfaccion: Tamano de la vivienda</td>
<td style="text-align: right;">2572</td>
<td style="text-align: right;">5.787546</td>
<td style="text-align: right;">3.769051</td>
<td style="text-align: right;">0.9231068</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: left;">Satis_calidad_viv</td>
<td style="text-align: left;">Grado de satisfaccion: Calidad de la vivienda</td>
<td style="text-align: right;">2572</td>
<td style="text-align: right;">5.787546</td>
<td style="text-align: right;">3.769051</td>
<td style="text-align: right;">0.9231068</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Frecue_peleas_calle</td>
<td style="text-align: left;">Frecuencia: Rinas o peleas callejeras</td>
<td style="text-align: right;">2564</td>
<td style="text-align: right;">6.080586</td>
<td style="text-align: right;">1.930577</td>
<td style="text-align: right;">1.1085527</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Frecue_robo</td>
<td style="text-align: left;">Frecuencia: Robos o asaltos</td>
<td style="text-align: right;">2556</td>
<td style="text-align: right;">6.373626</td>
<td style="text-align: right;">2.257433</td>
<td style="text-align: right;">1.1407089</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Frecue_trafico</td>
<td style="text-align: left;">Frecuencia: Trafico de drogas</td>
<td style="text-align: right;">2426</td>
<td style="text-align: right;">11.135531</td>
<td style="text-align: right;">2.447238</td>
<td style="text-align: right;">1.4447554</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Frecue_ruido_moles</td>
<td style="text-align: left;">Frecuencia: Ruidos molestos</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">5.824176</td>
<td style="text-align: right;">2.055231</td>
<td style="text-align: right;">1.1979485</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Frecue_amenzas</td>
<td style="text-align: left;">Frecuencia: Amenazas de vecinos</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">5.824176</td>
<td style="text-align: right;">1.316608</td>
<td style="text-align: right;">0.7553392</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Frecue_vecino_sucio</td>
<td style="text-align: left;">Frecuencia: problemas con vecinos para botar la basura</td>
<td style="text-align: right;">2567</td>
<td style="text-align: right;">5.970696</td>
<td style="text-align: right;">1.820413</td>
<td style="text-align: right;">1.1828553</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
<p>A partir de los&nbsp;resultados obtenidos podemos interpretar lo siguiente:</p>
<p>La tabla nos muestra que en promedio la mayoría de los encuestados no presentan mayores intenciones de cambiarse de hogar, a la hora de preguntarles se obtuvo una media de un 2.93 de una escala de 1 a 4, la que seria cercana a la alternativa de respuesta 3 (“No, porque estoy bien donde estoy”) lo que nos induce a pensar que hay una cierta estabilidad residencial;&nbsp;esta estabilidad podria verse motivada producto de los valores obtenidos en otras respuestas del tipo identitario como: alto sentido de pertenencia, identificación con el barrio y identificación con los vecinos ,teniendo valores en sus medias de 3.729, 3.724 y 3.635 respectivamente, los cuales actúan como un elemento disuasor ante el sentimiento de querer realizar un cambio de vivienda.&nbsp;</p>
<p>Por otra parte, los niveles de satisfacción con atributos en cuanto al entorno y la vivienda inciden ligereamente en la percepción individual, los encuestados muestran cierta conformidad a la hora de preguntarles sobre el tamaño y calidad de la vivienda, la cercanía que tienen con amigos, familiares, colegios y conectividad en donde sus valores van desde la media de 3.2 a 3.78 en escalas de 1 a 5, ubicandose aquellos valores entre las alternativas de respuesta “Ni satisfecho ni insatisfecho” y “Satisfecho” los cuales también le agrega cierto peso al querer mantenerse en su vivienda actual.&nbsp;</p>
<p>Ahora si abordamos las variables que podrían considerarse dentro del término de la frecuencia de diversas problemáticas al interior del barrio, estas no son indicadores del todo negativos; las variables como la frecuencia de ruidos molestos, amenazas entre vecinos, y problemas con la basuras presentan valores bajos que van desde 1.3 a 2, coincidendo con las alternativas de respuesta de “Nunca” o “Pocas veces”.</p>
<p>Ahora si nos vamos a las variables que abordan la frecuencia de problemas más extremos como lo serian robos, peleas callejeras o el tráfico de drogas estas variables muestran valores un poco más altos que los anteriores que van desde un 1.9 hasta un 2.4, siendo este, ek valor más alto el de la frecuencia del tráfico de drogas (2.44), pero aun asi estas respuesta se ubicarian entre las categorias de respuesta de “Nunca” o “Pocas veces”; esto igualmente se ve también reflejado en la variable de la satisfacción del barrio en cuanto a su seguridad en donde su media es de un 3.2 &nbsp;en una escala de 1 a 5 coincidente con la anternativa de respuesta de “Ni satisfecho ni insatisfecho” lo cual nos indica dos elementos:</p>
<p>En primera instancia, aquellos elementos son mas conciderados o percibidos por los encuestado y por ende considerados mas relevantes. Por lo que estas variables claramente inciden de manera más directa con la percepción que tienen los residentes en cuanto a su entorno debido a que los impacta de forma más directa.&nbsp;</p>
<p>Como conclusión podemos decir que la mayoría de los encuestados no presentan fuertes incidencias en querer realizar un cambio de vivienda debido a que se sienten en promedio cómodos en su hogar, ya sea producto a sentimientos positivos producidos por el barrio en si mismo como lo seria la identificación con el barrio o con su gente; además también una leve valoración positiva en&nbsp;base a la valoración del sector en lo que seria su conectividad, la cercanía a áreas verdes, limpieza, y/o cercanía con familia o amigos, los cuales al también tener valores altos jugarian un rol importante.</p>
<p>Por ultimo pese al tener valores del todo altos en todas las variables en lo referido a lo que podemos denominar como “una categoría exposición al riesgo”, se le podria considerar una suma a que los individuos no presenten mayores intenciones de querer llevar a cabo un cambio en sus residencias.&nbsp;</p>
</section>
<section id="analisis-descriptivo-de-los-graficos-de-las-variables" class="level2">
<h2 class="anchored" data-anchor-id="analisis-descriptivo-de-los-graficos-de-las-variables">3.2 Analisis descriptivo de los graficos de las variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>graph1 <span class="ot">&lt;-</span> sjPlot<span class="sc">::</span><span class="fu">plot_stackfrq</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data_2022, Barrio_ideal,</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                                Integra_barrio,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                                Identi_gente, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>                                Parte_barrio,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>                                Satis_seguridad,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>                                Satis_conectividad,</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>                                Satis_area_ocio,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>                                Satis_barrio_limp,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>                                Satis_cerca_trab,</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>                                Satis_cerca_coleg,</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>                                Satis_cerca_comerc,</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>                                Satis_cerca_amig_fami,</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>                                Satis_tamano_viv,</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>                                Satis_calidad_viv),</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">title =</span> <span class="st">"Grafico descriptivo variables de satisfacción y grado de acuerdo"</span>) <span class="sc">+</span></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>graph1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Preparación_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<p>A partir del los resultados del primer grafico se puede interpretar lo siguiente:</p>
<p>Las respuestas de los encuestados en lo referente a preguntas que miden el grado de satisfacción residencial o que se relacionan con el grado de acuerdo ante determinadas caracteristicas del barrio, estas se concentran en su mayoria en las categorias de respuestas de “De acuerdo” o “Totalmente de acuerdo” siendo aquellas dos categorias de respuestas las principales solvi contadas excepciones.</p>
<p>Aquellas excepciones serian las preguntas referidas a las de: satisfacción con la proximidad con familiares o amigos cercanos; satisfacción con proximidad a areas de comercio; satisdacción con cercania al luhgar de actividad principal; satisfacción con la belleza o limpieza; satisfacción de areas verdes y de recreación disponibles; la de satisfacción con la conectividad y la satisfacción con seguridad del barrio.</p>
<p>Estas variables pese a seguir presentando a la categoria de “De acuerdo” como la mayoritaria presentan la caracteristica de tener algunas de sus otraas categorias de respuesta con un distribución homogenea o similar (vease por ejemplo la pregunta referida a satisfacción con conectividad) y/o presentan la caracteristica de que otro categoria distinta a “Totalmente de acuerdo” es la segunda mas indicada; vease en: Grado de satisfacción con limpieza o belleza del barrio o Grado de satisfacción con areas verdes o de recreación disponible o por ultimo con el grado de satisfacción con la seguridad. Todas estas variables presentan como la segunda opción mayoritaria la categoria de respuesta de “En desacuerdo”.</p>
<p>Aquello se podria interpretar como el hecho de que al igual como se menciono en la interpretación de la tabla que; aquellas variables en las que tienen como segunda opción mayoritaria la categoria de “En desacuerdo” o una distinta de “Totalmente de acuerdo” son mas criticos y le entregan mayor importancia de forma directa a aquellos espectos que otros.</p>
<p>A su vez tambien aquellas categorias que presentan una concentración de sus respuestas en la categoria de “De acuerdo” o “Totalmente de acuerdo” pueden ser variables relevantes de cara al explicar el porque el encuestado no buscaria cambiar de hogar y que este a su vez mantenga su deseo de seguir en dicho hogar.</p>
<p>De forma general tambien se puede interpretar de forma general que la satisfacción en estas categorias/variables no habrian de afectar de forma general el deseo de cambiar de hogar aunque aquello quedaria pendiente de explorarse en mayor profundidad.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>graph2 <span class="ot">&lt;-</span> sjPlot<span class="sc">::</span><span class="fu">plot_stackfrq</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data_2022, Frecue_peleas_calle,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>                                              Frecue_robo,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                                              Frecue_trafico,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>                                              Frecue_ruido_moles,</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>                                              Frecue_amenzas,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>                                              Frecue_vecino_sucio),</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">title =</span> <span class="st">"Grafico descriptivo variables de frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>graph2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Preparación_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<p>A partir de los resultados del segundo grafico podemos decir lo siguiente:</p>
<p>Las respuestas de los encuestados respecto a situaciones conflictivas o problemáticas que afectan la convivencia barrial, tales como conflictos con vecinos por basura, amenazas, ruidos molestos, tráfico de drogas, robos riñas, muestran una tendencia general a concentrarse en categorías de respuestas más positivas , especialmente en lo que refiere a basura y amenazas, donde la mayoría de los encuestados no declara haber tenido experiencias negativas con mucha frecuencia, esto nos indica que en estos aspectos no hay una conflictividad mayor.</p>
<p>Sin embargo, si bien no hay porcentajes del todo altos existen ciertas variables que se apartan de la tendencia anterior, estas son las de ruidos molestos, tráfico de drogas, robos y riñas, presentan una distribución más dispersa en sus respuestas, podemos observar con mayor frecuencia categorías que indican experiencias negativas, ya sea ocasionales o incluso ya de forma más reiterada. Si bien en la mayoría de las opciones la mayoría de las respuestas son de la respuesta nunca, hay una presencia significativa de haber experimentado estas situaciones desde algunas veces hasta en casos más extremos que seria que ocurren siempre</p>
<p>Esto podríamos interpretarlo que las personas en estos aspectos específicos como el tráfico de drogas y ruidos molestos, las personas tienden a ser más críticas, lo que podría estar vinculado a una mayor sensibilidad o preocupación frente a estas problemáticas, siguiendo esto estas variables podrían tener un peso más significativo en el deseo de cambia de hogar, ya que implican condiciones de vida que afectan directamente la calidad del entorno.</p>
<p>Por otro lado, aquellas variables que presentan mayor concentración respuestas más positivas como el caso de la basura o amenazas podrían considerarse como factores que refuerzan la permanencia residencial, al no representar un motivo directo de insatisfacción o malestar significativo</p>
</section>
</section>
<section id="elementos-a-considerar-a-futuro" class="level1">
<h1>4. Elementos a considerar a futuro</h1>
<p>Creemos relevante considerar a futuro profundizar en la relación y comportamiento de las variables entre si; para aquello somos concientes de que no podemos tener 20 variables producto a que aquello podria dificultar el analisis o alargar innecesariamente.</p>
<p>Es producto a aquello que elaborariamos una serie de indices u escalas a partir de estas variables con el fin de facilitar nuestro analisis y poder medir y/o relacionar fenomenos o elementos mas complejos con nuestra variable o tema de interes.</p>
<p>Por ejemplo las determinates que consideramos para la investigación de este tema de trabajo (que eran un total de 4) podrian ser presentada a traves o por medio de estos indices u escalas.</p>
<p>Tambien dejamos pediente de considerar a futuro la posibilidad de recodificar nuestra variable dependiente cambio de hogar (la cual cuenta con 4 categorias de respuesta) por un total de 2, o sea volverla una variable dummy para representar de mejor manera aquel fenomeno que nos disponemos a investigar.</p>
</section>
<section id="bibliografia" class="level1">
<h1>5. Bibliografia</h1>
<p>Producto a una serie de errores que sufrimos con el gestor bibliografico de Zotero, no pudimos incluir la bibliografia segun como estaba indicada en la pauta del trabajo, para dejar registro de la bibliografia que si empleamos dejamos registro de esta en el siguiente apartado:</p>
<p>Amérigo, M., &amp; Aragonés, J. I. (1988). Satisfacción residencial en un barrio remodelado: Predictores físicos y sociales. International Journal of Social Psychology, 3(1), 61–70. <a href="https://doi.org/10.1080/02134748.1988.10821574" class="uri">https://doi.org/10.1080/02134748.1988.10821574</a></p>
<p>Martínez Ibarra, Alejandra, &amp; Ibarra Salazar, Jorge. (2017). Los determinantes de la satisfacción residencial en México. Estudios demográficos y urbanos, 32(2), 283-313. <a href="https://doi.org/10.24201/edu.v32i2.1635" class="uri">https://doi.org/10.24201/edu.v32i2.1635</a></p>
<p>Sabatini, F. (2011). La segregación social del espacio en las ciudades de América Latina. <a href="https://doi.org/10.18235/0009848" class="uri">https://doi.org/10.18235/0009848</a></p>
</section>
<section id="trabajo-2" class="level1">
<h1>Trabajo 2:</h1>
</section>
<section id="asociación-de-variables-en-base-a-la-construcción-de-una-tabla-de-correlaciones-y-contrucción-de-índice-de-satisfacción-residencial." class="level1">
<h1>Asociación de variables en base a la construcción de una tabla de correlaciones y contrucción de índice de “Satisfacción residencial”.</h1>
<section id="introducción-1" class="level2">
<h2 class="anchored" data-anchor-id="introducción-1">1. Introducción</h2>
<p>El presente trabajo 2 se enmarca como continuación del trabajo 1.</p>
<p>Este trabajo 2 se centra tal como lo indica el título en medir la asociación de las variables que fueron seleccionadas en el trabajo anterior; para aquello se realizaría una tabla de correlaciones la cual mediría la covariancia entre ambas variables; siendo aquello seria la forma que tendríamos para saber si nuestras variables se encuentran asociadas entre sí y de qué forma.</p>
<p>Posterior a la obtención de la tabla de correlaciones, nos dispondremos a realizar un indice con la cual confeccionaríamos una medición del concepto de satisfacción residencial.</p>
<p>Para entender el porqué de la confección de un indice para la medición del concepto de “Satisfacción residencial” es necesaria adentrarnos en el siguiente punto:</p>
<section id="recapitulación-del-trabajo-anterior-y-el-porqué-de-la-elaboración-de-un-índice-de-medición-de-la-satisfacción-residencial." class="level3">
<h3 class="anchored" data-anchor-id="recapitulación-del-trabajo-anterior-y-el-porqué-de-la-elaboración-de-un-índice-de-medición-de-la-satisfacción-residencial.">1.1 Recapitulación del trabajo anterior y el porqué de la elaboración de un índice de medición de la “Satisfacción residencial”.</h3>
<p>En el trabajo anterior referido a las “Determinantes residenciales que motivan la decisión del cambio de hogar en Chile” establecimos que nuestro concepto central a investigar sería el de “satisfacción residencial” concepto al cual lo entendemos desde de la definición de (Amérigo, <em>et al</em>, 2014) como: “como una evaluación subjetiva que realiza el individuo sobre sus condiciones de su vivienda y el entorno inmediato en el cual se encuentra, tanto en lo social como en lo físico”.</p>
<p>Además, establecimos como nuestra hipótesis de investigación el que: “se espera que a medida que disminuya la satisfacción residencial tanto en sus aspectos físicos y sociales, aumente la probabilidad que una persona decida cambiarse de hogar”.</p>
<p>Es así que sería necesaria la elaboración de una escala con la cual podríamos elaborar una medición que contemple nuestra definición del concepto de “Satisfacción residencial” y que a su vez, esta pueda poner a prueba nuestra hipótesis de investigación respondiendo al último párrafo del punto anterior.</p>
</section>
</section>
<section id="preparación-del-trabajo" class="level2">
<h2 class="anchored" data-anchor-id="preparación-del-trabajo">2. Preparación del trabajo</h2>
<section id="instalación-de-paquetes-1" class="level3">
<h3 class="anchored" data-anchor-id="instalación-de-paquetes-1">2.1. Instalación de paquetes:</h3>
<p>Los paquetes que empleamos para la elaboración de este trabajo serían los mismo que los del trabajo 1; con la excepción de dos paquetes más que se sumarian los cuales serían: GGally y corrplot.</p>
<p>Estos se utilizarían para la elaboración de las correlaciones y la elaboración de de los gráficos de estos mismos respectivamente.</p>
<p>Es necesario un paquete extra para la elaboración del índice que los que tenemos previamente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled,</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>               dplyr,</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>              stargazer, </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>              sjmisc, </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>              summarytools, </span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>              kableExtra, </span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>              sjPlot,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>              corrplot, </span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>              sessioninfo, </span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>              ggplot2,</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>              knitr,</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>              GGally,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>              corrplot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="descarga-de-la-base-de-datos-1" class="level3">
<h3 class="anchored" data-anchor-id="descarga-de-la-base-de-datos-1">2.2. Descarga de la base de datos</h3>
<p>Nuestra base de datos con la que nos dispondríamos a trabajar seria la “Encuesta Longitudinal Social de Chile” realizada por el COES (Centro de Estudios de Conflicto y Cohesión social).</p>
<p>Y esta base la descargamos desde internet con el siguiente enlace:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://dataverse.harvard.edu/api/access/datafile/7245118"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="selección-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="selección-de-variables">2.3. Selección de variables</h3>
<p>Para la realización de este trabajo continuaremos trabajando con gran parte de las variables seleccionadas en el trabajo anterior (el trabajo 1) solo que se descartaran un total de 6 variables de las 21 que eran originalmente.</p>
<p>Estas variables que descartamos serian: t09_01; 09_02; t09_03; t11_01; t11_03 y t11_04 referidas a las siguientes mediciones:</p>
<p>t09_01: Frecuencia: Rinnias o peleas callejeras (nombrada como: Frecue_peleas_calle)</p>
<p>t09_02: Frecuencia: Robos o asaltos a personas, casas y/o vehiculos (nombrada como: Frecue_robo)</p>
<p>t09_03: Frecuencia: Trafico de drogas (nombrada como: Frecue_trafico)</p>
<p>t11_01: Frecuencia: Ruidos molestos (como musica fuerte o gritos) (nombrada como: Frecue_ruido_moles)</p>
<p>t11_03: Frecuencia: Amenazas, insultos u ofensas de vecinos del barrioFrecuencia: Amenazas, insultos u ofensas de vecinos del barrio (nombrada como: Frecue_amenzas)</p>
<p>t11_04: Frecuencia: Problemas por vecinos botan basura o similar (nombrada como: Frecue_vecino_sucio)</p>
<p>Es así como nos quedaríamos con las siguientes 15 variables:</p>
<p>t02_01: Grado de acuerdo: Este es el barrio ideal para mi (nombrada como: Barrio_ideal)</p>
<p>t02_02: Grado de acuerdo: Me siento integrado/a en este barrio (nombrada como: Integra_barrio)</p>
<p>t02_03: Grado de acuerdo: Me identifico con la gente de este barrio (nombrada como: Identi_gente)</p>
<p>t02_04: Grado de acuerdo: Este barrio es parte de mi (nombrada como: Parte_barrio)</p>
<p>t05: Tiene planeado cambiarse de casa/departamento en el proximo annio (nombrada como: Cambio_hogar)</p>
<p>t06_01: Grado de satisfacción: Seguridad del barrio (nombrada como: Satis_seguridad)</p>
<p>t06_02: Grado de satisfacción: Conectividad (nombrada como: Satis_conectividad)</p>
<p>t06_03: Grado de satisfacción: Áreas verdes y de recreación disponibles (nombrada como: Satis_area_ocio)</p>
<p>t06_04: Grado de satisfacción: Limpieza y belleza del barrio (nombrada como: Satis_barrio_limp)</p>
<p>t06_05: Grado de satisfacción: Proximidad al lugar de actividad principal (nombrada como: Satis_cerca_trab)</p>
<p>t06_06: Grado de satisfacción: Proximidad a colegios de buena calidad (nombrada como: Satis_cerca_coleg)</p>
<p>t06_07: Grado de satisfacción: Proximidad a áreas de comercio (nombrada como: Satis_cerca_comerc)</p>
<p>t06_08: Grado de satisfacción: Proximidad con familiares y/o amigos cercanos (nombrada como: Satis_cerca_amig_fami)</p>
<p>t07_01: Grado de satisfacción: Tamannio de la vivienda (nombrada como: Satis_tamano_viv)</p>
<p>t07_02: Grado de satisfacción: Calidad de la vivienda (nombrada como: Satis_calidad_viv)</p>
<p>Para seleccionar dichas variables crearíamos una sub-base la cual utilizaremos a lo largo de todo este trabajo la cual sería llamada como: “proc_data_2022_tr2.</p>
<p>Esta sub-base seria creada a partir de la sub-base anteriormente realizada en el primer trabajo llamada proc_data_2022; de esta última seleccionamos las variables que utilizaremos para este trabajo 2 y aquellas no seleccionadas serian descartas (las cuales serían las variables anteriormente mencionadas).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2 <span class="ot">&lt;-</span> proc_data_2022 <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Barrio_ideal,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>         Integra_barrio,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>         Identi_gente, </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>         Parte_barrio,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>         Cambio_hogar,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>         Satis_seguridad,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>         Satis_conectividad,</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>         Satis_area_ocio,</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>         Satis_barrio_limp,</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>         Satis_cerca_trab,</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>         Satis_cerca_coleg,</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>         Satis_cerca_comerc,</span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>         Satis_cerca_amig_fami,</span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>         Satis_tamano_viv,</span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>         Satis_calidad_viv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hacemos este proceso de este modo porque así nos ahorramos el tener que reetiquetar cada una de las variables.</p>
</section>
<section id="tratamiento-de-los-casos-perdidos-1" class="level3">
<h3 class="anchored" data-anchor-id="tratamiento-de-los-casos-perdidos-1">2.4. Tratamiento de los casos perdidos</h3>
<p>Además de ahorrarnos el tener que reetiquetar cada una de las variables con el método anterior, nos ahorramos el tener que tratar los casos perdidos correspondientes a (NS/NR) correspondiente a “no sabe”/“no responde” ya que estos fueron tratados en la sub-base anterior en el trabajo 1.</p>
<p>Aun así, para aclararlo dichos valores perdido de (NS/NR) correspondientes a los valores de -888 y -999 fueron marcados como NA.</p>
<p>Dichos valores fueron retenidos en la base de datos, pero son excluidos como valores faltantes en la variable al momento de analizarlos en ese momento en cualquier operación.</p>
<p>Tal seria en el caso del cálculo de medias; la confección de tabla de correlaciones y el índice que realizaríamos para este trabajo. Este tratamiento de los casos perdidos (NA) que realizamos en este trabajo seria conocido como PAIRWISE DELETION.</p>
</section>
<section id="tratamiento-de-las-variables." class="level3">
<h3 class="anchored" data-anchor-id="tratamiento-de-las-variables.">2.5. Tratamiento de las variables.</h3>
<section id="tratamiento-de-la-variable-cambio_hogar" class="level4">
<h4 class="anchored" data-anchor-id="tratamiento-de-la-variable-cambio_hogar">2.5.1. Tratamiento de la variable Cambio_hogar</h4>
<p>Respecto al tratamiento de las variables, para este trabajo realizaremos uno de los aspectos que consideramos en el punto 4 del trabajo anterior (trabajo 1) y que sería el tratamiento que tendría la variable Cambio_hogar.</p>
<p>Esta se encuentra codificada en cuatro categorías de respuesta: 1 - “Si, a otro barrio de la comuna”; 2 - “Si, a otra comuna”; 3 - “No, porque estoy bien donde estoy” y 4 - “No, no puedo aunque quisiera”.</p>
<p>Para este trabajo recodificaremos dicha variable para que esta pase a ser dummy (categorizada con valores referentes a 0 y 1).</p>
<p>Para eso englobaríamos las categorías de respuesta 1 y 2 en la alternativa de respuesta: “Ha pensado en cambiarse de hogar” mientras que las respuestas 3 y 4 serían englobadas en la alternativa de respuesta: “No ha pensado en cambiarse de hogar”.</p>
<p>Para eso haríamos lo siguiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar,</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                                               <span class="st">"c(1,2)=1; c(3,4)=2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Recodificamos las alternativas de respuestas 1 y 2 como 1; mientras que las alternativas de repuesta 3 y 4 como 2.</p>
<p>Posterior a aquello le asignamos a la categoría de respuesta 1, el valor de 0 y a la categoría de respuesta 2, el valor de 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar, <span class="st">"1=0;2=1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hicimos esos dos pasos en vez de haberlo realizado directamente para evitar errores en el tratamiento de esta variable en la sub-base.</p>
<p>Asignamos dichas categorías de respuesta a los valores de las variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar,</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">labels =</span> <span class="fu">c</span> (<span class="st">"Ha pensado en cambiarse de hogar"</span>,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>                                                      <span class="st">"No ha pensado en cambiarse de hogar"</span>),</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">levels =</span> <span class="fu">c</span> (<span class="dv">0</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Y vemos la categoría/etiqueta de esta</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<p>NULL indicaría que esta variable carece de categorías de respuesta o una etiqueta en si misma así que se la procederíamos a agregar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar, <span class="at">label =</span> <span class="st">"Cambio hogar"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Procedemos a realizar una tabla para ver si se aplicó la categoría a la variable y si se aplicaron las categorías de respuesta:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cambio hogar (x) &lt;categorical&gt; 
# total N=2730 valid N=2536 mean=1.80 sd=0.40

Value                               |    N | Raw % | Valid % | Cum. %
---------------------------------------------------------------------
Ha pensado en cambiarse de hogar    |  497 | 18.21 |   19.60 |  19.60
No ha pensado en cambiarse de hogar | 2039 | 74.69 |   80.40 | 100.00
&lt;NA&gt;                                |  194 |  7.11 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Ha pensado en cambiarse de hogar"    "No ha pensado en cambiarse de hogar"</code></pre>
</div>
</div>
<p>Como podemos ver ambas se pudieron aplicar correctamente y las dejamos en esta parte del trabajo por fines descriptivos y para su consulta; más en si se procederá a devolverlas a su forma numérica porque para el próximo paso referido a la tabla de correlaciones es necesario que todas las variables sean numéricas.</p>
<p>Así que de volvemos ambas variables a sus valores numéricos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar, <span class="st">"Ha pensado en cambiarse de hogar"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"No ha pensado en cambiarse de hogar"</span> <span class="ot">=</span> <span class="dv">1</span> ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Comprobamos que se hallan aplicado los cambios correctamente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_2022_tr2<span class="sc">$</span>Cambio_hogar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=2730 valid N=2536 mean=0.80 sd=0.40

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    0 |  497 | 18.21 |   19.60 |  19.60
    1 | 2039 | 74.69 |   80.40 | 100.00
 &lt;NA&gt; |  194 |  7.11 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="tratamiento-del-resto-de-variables-de-la-sub-base" class="level4">
<h4 class="anchored" data-anchor-id="tratamiento-del-resto-de-variables-de-la-sub-base">2.5.2. Tratamiento del resto de variables de la sub-base</h4>
<p>Para el resto de las variables el único tratamiento que estas recibirían sería el de una recodificación de los valores de su categoría de respuesta.</p>
<p>Todas nuestras variables tienen como categoría de respuestas valores que van de 1 a 5; en este apartado se recodificaran dichos valores para que pasen a ser de 0 a 4; esto se realizaría para facilitar la interpretación del futuro índice que realizaremos facilitándonos así la interpretación de sus valores partiendo de un mínimo que seria 0 y el máximo correspondiente al índice.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Barrio_ideal <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Barrio_ideal, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Integra_barrio <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Integra_barrio, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Identi_gente <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Identi_gente, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Parte_barrio <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Parte_barrio, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_seguridad <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_seguridad, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_conectividad <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_conectividad, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-13"><a href="#cb73-13" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_area_ocio <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_area_ocio, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-14"><a href="#cb73-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-15"><a href="#cb73-15" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_barrio_limp <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_barrio_limp, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-16"><a href="#cb73-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-17"><a href="#cb73-17" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_trab <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_trab, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-18"><a href="#cb73-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-19"><a href="#cb73-19" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_coleg <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_coleg, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-20"><a href="#cb73-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-21"><a href="#cb73-21" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_comerc <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_comerc, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-22"><a href="#cb73-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-23"><a href="#cb73-23" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_amig_fami <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_cerca_amig_fami, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-24"><a href="#cb73-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-25"><a href="#cb73-25" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_tamano_viv <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_tamano_viv, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span>
<span id="cb73-26"><a href="#cb73-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-27"><a href="#cb73-27" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2<span class="sc">$</span>Satis_calidad_viv <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data_2022_tr2<span class="sc">$</span>Satis_calidad_viv, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4; else=NA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La primera parte del código que estaríamos realizando referidos la car::recode se utiliza para indicarle a Rstudios que queremos realizar la acción de recode del paquete car en específico y evitar confusiones debido a que el paquete dplyr también tiene la función de recode.</p>
<p>La última parte de este código referido al de “esle=NA” se utiliza para indicar que no se consideren los valores omitidos.</p>
</section>
<section id="guardamos-la-base-de-datos" class="level4">
<h4 class="anchored" data-anchor-id="guardamos-la-base-de-datos">2.5.3. Guardamos la base de datos</h4>
<p>Guardamos la base de datos que hemos realizado en la carpeta de imput para poder cargarla en trabajos futuros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_data_2022_tr2, <span class="at">file =</span> <span class="st">"C:/Users/jmuno/OneDrive/Desktop/OFC_R/Ojeda-Tognarelli-Trabajo-1/imput/proc_data_2022_tr2.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="tabla-de-correlaciones" class="level2">
<h2 class="anchored" data-anchor-id="tabla-de-correlaciones">3. Tabla de Correlaciones</h2>
<p>Como se mencionó con anterioridad para realizar una tabla de correlaciones, se necesita que todas las variables de la sub-base sean numéricas; teniendo aquel prerrequisito cumplido la tabla de correlaciones se elaboraría y se vería de la siguiente manera:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>Correlacion_2022 <span class="ot">&lt;-</span> <span class="fu">cor</span>(proc_data_2022_tr2, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>Correlacion_2022</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Barrio_ideal Integra_barrio Identi_gente Parte_barrio
Barrio_ideal             1.0000000      0.6427239    0.5943161    0.6012292
Integra_barrio           0.6427239      1.0000000    0.7141957    0.6597068
Identi_gente             0.5943161      0.7141957    1.0000000    0.7141809
Parte_barrio             0.6012292      0.6597068    0.7141809    1.0000000
Cambio_hogar             0.2552385      0.2225650    0.2279617    0.2413854
Satis_seguridad          0.4903438      0.3944064    0.3681947    0.3555369
Satis_conectividad       0.2484629      0.2560607    0.2202607    0.2374892
Satis_area_ocio          0.2641014      0.2339518    0.1970724    0.2013428
Satis_barrio_limp        0.3711891      0.3008056    0.2705660    0.2879797
Satis_cerca_trab         0.2503657      0.2444155    0.2346911    0.2534620
Satis_cerca_coleg        0.2689071      0.2429342    0.2516011    0.2316830
Satis_cerca_comerc       0.2184614      0.1923038    0.2026662    0.1989941
Satis_cerca_amig_fami    0.1909956      0.2431143    0.2354464    0.2274377
Satis_tamano_viv         0.2715220      0.2290637    0.2131751    0.2294790
Satis_calidad_viv        0.2715220      0.2290637    0.2131751    0.2294790
                      Cambio_hogar Satis_seguridad Satis_conectividad
Barrio_ideal            0.25523852       0.4903438         0.24846292
Integra_barrio          0.22256502       0.3944064         0.25606072
Identi_gente            0.22796169       0.3681947         0.22026066
Parte_barrio            0.24138539       0.3555369         0.23748916
Cambio_hogar            1.00000000       0.1624786         0.05491364
Satis_seguridad         0.16247862       1.0000000         0.29471196
Satis_conectividad      0.05491364       0.2947120         1.00000000
Satis_area_ocio         0.10764799       0.3097648         0.27078750
Satis_barrio_limp       0.14132711       0.4386451         0.23513124
Satis_cerca_trab        0.10301294       0.2103018         0.31262378
Satis_cerca_coleg       0.10255191       0.2396348         0.32610505
Satis_cerca_comerc      0.05418692       0.1845910         0.38217686
Satis_cerca_amig_fami   0.08741042       0.1363843         0.22157053
Satis_tamano_viv        0.12738157       0.1992403         0.19635428
Satis_calidad_viv       0.12738157       0.1992403         0.19635428
                      Satis_area_ocio Satis_barrio_limp Satis_cerca_trab
Barrio_ideal                0.2641014         0.3711891        0.2503657
Integra_barrio              0.2339518         0.3008056        0.2444155
Identi_gente                0.1970724         0.2705660        0.2346911
Parte_barrio                0.2013428         0.2879797        0.2534620
Cambio_hogar                0.1076480         0.1413271        0.1030129
Satis_seguridad             0.3097648         0.4386451        0.2103018
Satis_conectividad          0.2707875         0.2351312        0.3126238
Satis_area_ocio             1.0000000         0.5625711        0.2748238
Satis_barrio_limp           0.5625711         1.0000000        0.2850074
Satis_cerca_trab            0.2748238         0.2850074        1.0000000
Satis_cerca_coleg           0.3119687         0.3034815        0.3989559
Satis_cerca_comerc          0.2700174         0.2384501        0.3508560
Satis_cerca_amig_fami       0.1650992         0.1382057        0.2631998
Satis_tamano_viv            0.1508487         0.2102652        0.1663639
Satis_calidad_viv           0.1508487         0.2102652        0.1663639
                      Satis_cerca_coleg Satis_cerca_comerc
Barrio_ideal                  0.2689071         0.21846142
Integra_barrio                0.2429342         0.19230377
Identi_gente                  0.2516011         0.20266621
Parte_barrio                  0.2316830         0.19899411
Cambio_hogar                  0.1025519         0.05418692
Satis_seguridad               0.2396348         0.18459097
Satis_conectividad            0.3261051         0.38217686
Satis_area_ocio               0.3119687         0.27001740
Satis_barrio_limp             0.3034815         0.23845010
Satis_cerca_trab              0.3989559         0.35085600
Satis_cerca_coleg             1.0000000         0.52725026
Satis_cerca_comerc            0.5272503         1.00000000
Satis_cerca_amig_fami         0.2604199         0.26641089
Satis_tamano_viv              0.1805262         0.19830349
Satis_calidad_viv             0.1805262         0.19830349
                      Satis_cerca_amig_fami Satis_tamano_viv Satis_calidad_viv
Barrio_ideal                     0.19099565        0.2715220         0.2715220
Integra_barrio                   0.24311433        0.2290637         0.2290637
Identi_gente                     0.23544636        0.2131751         0.2131751
Parte_barrio                     0.22743772        0.2294790         0.2294790
Cambio_hogar                     0.08741042        0.1273816         0.1273816
Satis_seguridad                  0.13638433        0.1992403         0.1992403
Satis_conectividad               0.22157053        0.1963543         0.1963543
Satis_area_ocio                  0.16509920        0.1508487         0.1508487
Satis_barrio_limp                0.13820573        0.2102652         0.2102652
Satis_cerca_trab                 0.26319984        0.1663639         0.1663639
Satis_cerca_coleg                0.26041993        0.1805262         0.1805262
Satis_cerca_comerc               0.26641089        0.1983035         0.1983035
Satis_cerca_amig_fami            1.00000000        0.1641959         0.1641959
Satis_tamano_viv                 0.16419590        1.0000000         1.0000000
Satis_calidad_viv                0.16419590        1.0000000         1.0000000</code></pre>
</div>
</div>
<p>Debido a las limitaciones que tiene Rstudios y Quarto la tabla de correlaciones se vería de aquella manera, aun así, ahí otras alternativas que se pueden realizar para facilitar el aspecto referido a la confección he interpretación de la tabla de correlaciones.</p>
<p>La tabla de correlaciones también se podría realizar de la siguiente manera:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_corr</span>(proc_data_2022_tr2, <span class="at">triangle =</span> <span class="st">"lower"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de acuerdo: Pertinencia barrio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de acuerdo: Integracion barrio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de acuerdo: Identifica con gente<br>
del barrio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de acuerdo: Forma parte del barrio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Cambio_hogar</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Seguridad del<br>
barrio barrio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Conectividad</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Cercania a areas<br>
verdes o lugares de ocio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Limpieza o<br>
belleza del barrio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Cercania al lugar<br>
de trabajo o actividad pricipal</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Proximidad o<br>
cercania a colegios de calidad</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Cercania a<br>
lugares de comercio</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Cercania con<br>
amigos/familiares</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Tamano de la<br>
vivienda</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Grado de satisfaccion: Calidad de la<br>
vivienda</td>
</tr>
<tr class="even">
<td style="font-style: italic">Grado de acuerdo: Pertinencia barrio</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Grado de acuerdo: Integracion barrio</td>
<td style="text-align: center; padding: 0.2cm;">0.643<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Grado de acuerdo: Identifica con gente<br>
del barrio</td>
<td style="text-align: center; padding: 0.2cm;">0.594<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.714<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Grado de acuerdo: Forma parte del barrio</td>
<td style="text-align: center; padding: 0.2cm;">0.601<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.660<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.714<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Cambio_hogar</td>
<td style="text-align: center; padding: 0.2cm;">0.255<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.223<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.228<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.241<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Grado de satisfaccion: Seguridad del<br>
barrio barrio</td>
<td style="text-align: center; padding: 0.2cm;">0.490<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.394<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.368<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.356<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.162<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Grado de satisfaccion: Conectividad</td>
<td style="text-align: center; padding: 0.2cm;">0.248<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.256<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.220<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.237<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.055<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">0.295<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Grado de satisfaccion: Cercania a areas<br>
verdes o lugares de ocio</td>
<td style="text-align: center; padding: 0.2cm;">0.264<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.234<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.197<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.201<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.108<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.310<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.271<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Grado de satisfaccion: Limpieza o<br>
belleza del barrio</td>
<td style="text-align: center; padding: 0.2cm;">0.371<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.301<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.271<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.288<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.141<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.439<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.235<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.563<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Grado de satisfaccion: Cercania al lugar<br>
de trabajo o actividad pricipal</td>
<td style="text-align: center; padding: 0.2cm;">0.250<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.244<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.235<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.253<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.103<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.210<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.313<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.275<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.285<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Grado de satisfaccion: Proximidad o<br>
cercania a colegios de calidad</td>
<td style="text-align: center; padding: 0.2cm;">0.269<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.243<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.252<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.232<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.103<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.240<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.326<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.312<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.303<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.399<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Grado de satisfaccion: Cercania a<br>
lugares de comercio</td>
<td style="text-align: center; padding: 0.2cm;">0.218<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.192<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.203<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.199<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.054<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">0.185<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.382<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.270<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.238<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.351<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.527<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Grado de satisfaccion: Cercania con<br>
amigos/familiares</td>
<td style="text-align: center; padding: 0.2cm;">0.191<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.243<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.235<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.227<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.087<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.136<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.222<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.165<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.138<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.263<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.260<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.266<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Grado de satisfaccion: Tamano de la<br>
vivienda</td>
<td style="text-align: center; padding: 0.2cm;">0.272<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.229<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.213<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.229<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.127<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.199<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.196<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.151<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.210<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.166<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.181<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.198<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.164<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Grado de satisfaccion: Calidad de la<br>
vivienda</td>
<td style="text-align: center; padding: 0.2cm;">0.272<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.229<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.213<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.229<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.127<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.199<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.196<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.151<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.210<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.166<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.181<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.198<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.164<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">1.000<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td colspan="16" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Aun así, para fines de este trabajo optaríamos por realizar la tabla de correlaciones de la siguiente manera con el siguiente código:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(Correlacion_2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Preparación_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="1536"></p>
</figure>
</div>
</div>
</div>
<p>Optamos por esta forma de realizar la tabla de correlaciones porque esta tabla es la que contendría mayor cantidad de información referente a la asociación de las variables por sí misma.</p>
<p>Cuenta con el valor exacto de la asociación en la parte inferior de la tabla y esta se remarca con color azul cuando es positiva y a mayor asociación más intenso es dicho color; en caso de que no exista asociación entre las variables el valor de los numero se vería con una tonalidad translucida (y en caso de que la asociación sea negativa esta se remarcaría con color rojo y a mayor dicha asociación más intenso seria dicho color).</p>
<p>En la parte superior de la tabla se contaría con figuras de círculos que representaría de manera descriptiva las correlaciones entre las variables; mientras mayor sea el tamaño de circulo y más intenso su color aquello indicaría que es mayor la asociación de las variables.</p>
<p>Y el color de los círculos seguiría respondiendo a la misma lógica de asociación de las variables que los numero: Azul - Correlación positiva; Translucido - Poca correlación; Rojo - Asociación negativa.</p>
<p>Con dicha tabla (o tablas en caso de que se quiera considerar las tablas anteriores) podemos interpretar lo siguiente:</p>
<section id="intrepretación-de-la-tabla-de-correlaciones" class="level3">
<h3 class="anchored" data-anchor-id="intrepretación-de-la-tabla-de-correlaciones">3.1. Intrepretación de la Tabla de correlaciones</h3>
<p>Dentro del conjunto de variables analizadas, destacamos aquellas que presentan correlaciones fuertes, ya que son menos frecuentes en comparación con correlaciones de magnitud baja o moderada. En este caso, las primeras a considerar son las relaciones más significativas que se observan entre variables que capturan distintos aspectos del sentido de pertenencia e integración en el barrio, lo que indica una estrecha conexión entre estos elementos.</p>
<p>En primer lugar, encontramos una correlación alta (r = 0.643) entre el grado de acuerdo con la integración al barrio y el sentimiento de pertenencia al barrio. Esta asociación sugiere que, a mayor percepción de integración, es decir, sentirse parte activa del funcionamiento del barrio mayor es también el sentido de pertenencia. Esto puede explicarse porque las personas que se involucran más con su entorno tienden a desarrollar un vínculo más fuerte con su comunidad. La variable identificación con la gente del barrio también muestra una correlación fuerte con dos indicadores: pertenencia al barrio (r = 0.594) e integración al barrio (r = 0.714). Esto refleja que cuanto más se identifican las personas con los otros vecinos, es decir, sienten que comparten valores, intereses o formas de vida, mayor es tanto su sentido de pertenencia como su percepción de integración. En otras palabras, el reconocimiento y la afinidad con los otros residentes fortalece la construcción del vínculo comunitario.</p>
<p>Finalmente, el grado de acuerdo con formar parte del barrio se correlaciona fuertemente con pertenencia al barrio (r = 0.601), integración al barrio (r = 0.660) e identificación con la gente del barrio (r = 0.714). Estas relaciones refuerzan la idea de que la percepción de formar parte de una comunidad no es algo aislado, sino que se basa en la experiencia concreta de pertenecer, integrarse y reconocerse en los demás miembros del barrio.</p>
<p>Estas correlaciones fuertes se explican porque todas las variables mencionadas giran en torno a dimensiones relacionadas con el sentido de comunidad. Conceptualmente, pertenencia, integración, identificación y aceptación de formar parte son componentes que se refuerzan mutuamente. Quien se siente integrado probablemente se involucra en la vida comunitaria, lo que alimenta su sentido de pertenencia el sentirse parte del grupo lleva a una mayor identificación con las personas que lo componen, en donde se ven aspectos que refuerzan los lazos sociales y el bienestar.</p>
<p>Ahora dejando atrás aquellas variables de una dimensión de comunidad, pasamos con aquellas variables vinculadas con el entorno físico del barrio como lo son la variable de grado de satisfacción con la limpieza o belleza del barrio en correlación con la satisfacción de la cercanía a áreas verdes o lugares de ocio donde presentan una correlación significativa de (r=0.563) es decir que hay una relación bastante fuerte, esto lo podríamos interpretar como aquellos lugares que presentan lugares de ocio o áreas verdes son considerados más limpios o bellos por las personas, es decir que estos aspectos.</p>
<p>Por ultimo aquellas variables que presentan una correlación bastante fuerte son las variables de grado de satisfacción con la calidad de la vivienda, con las variables grado de satisfacción con el tamaño de la vivienda(r=1), en este proponemos dos tipos de interpretaciones distintas, La primera sugiere que los encuestados tienden a asociar directamente la calidad con el tamaño, considerando que una vivienda más grande implica una mayor calidad. La segunda posibilidad es que los participantes hayan interpretado ambas preguntas como equivalentes, lo que habría llevado a responder de forma muy similar en ambos ítems. Esta percepción solapada podría explicar la fuerte correlación observada.</p>
<p>El objetivo central de nuestro análisis es identificar qué variables (y dimensiones de la satisfacción residencial) podrían influir de manera importante en la decisión de cambiar de hogar. Sin embargo, al revisar las correlaciones entre las variables analizadas y la variable cambio de hogar, observamos que ninguna de las asociaciones alcanza un nivel fuerte o significante que pueda ser considerado como importante, la variable que tiene la correlación más alta es entre cambio de hogar y la variable Grado de acuerdo con la pertinencia del barrio (0.255), es decir una correlación pequeña. Esto sugiere que, dentro del conjunto de variables consideradas, ninguna parece tener un impacto significativo por sí sola en la decisión de mudanza. En términos analíticos, esto implica que estas variables independientes, de forma individual, no logran explicar con fuerza la variación observada en la variable dependiente.</p>
</section>
</section>
<section id="elaboración-del-índice-de-satisfacción-residencial" class="level2">
<h2 class="anchored" data-anchor-id="elaboración-del-índice-de-satisfacción-residencial">4. Elaboración del índice de “Satisfacción residencial”</h2>
<p>Habiendo realizado ya la tabla de correlaciones y posteriormente habiendo concluido por medio de su interpretación que ninguna de las variables independientes es capaz de explicar o provocar por sí misma un cambio en la variable dependiente; es que procederíamos a realizar un índice que considere el concepto de “Satisfacción residencial”.</p>
<p>Dicho índice estaría elaborado a partir de la consideración de todas las variables independientes en su conjunto. con la cual creemos que se lograría representar de manera más precisa la complejidad del concepto que se está investigando; además contaría con el respaldo teórico de los textos empleados como definición teórica del concepto de “Satisfacción residencial” en el trabajo 1.</p>
<section id="medición-de-la-consistencia-interna-del-índice" class="level3">
<h3 class="anchored" data-anchor-id="medición-de-la-consistencia-interna-del-índice">4.1. Medición de la consistencia interna del índice</h3>
<p>Para poder realizar un índice en primera instancia requeriríamos del saber si todas las variables tienen consistencia entre sí; para aquello sería necesario medir la consistencia interna de las variables.</p>
<p>Para poder realizar aquello utilizaremos el siguiente código:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(Correlacion_2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.smooth(r): Matrix was not positive definite, smoothing was done</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0
In smc, smcs &lt; 0 were set to .0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = Correlacion_2022)

  raw_alpha std.alpha G6(smc) average_r S/N median_r
      0.85      0.85    0.86      0.27 5.5     0.24

    95% confidence boundaries 
      lower alpha upper
Feldt   0.7  0.85  0.94

 Reliability if an item is dropped:
                      raw_alpha std.alpha G6(smc) average_r S/N var.r med.r
Barrio_ideal               0.83      0.83    0.84      0.26 4.8 0.021  0.23
Integra_barrio             0.83      0.83    0.84      0.26 4.9 0.019  0.23
Identi_gente               0.83      0.83    0.84      0.26 4.9 0.019  0.24
Parte_barrio               0.83      0.83    0.84      0.26 4.9 0.020  0.23
Cambio_hogar               0.85      0.85    0.86      0.29 5.7 0.022  0.24
Satis_seguridad            0.84      0.84    0.85      0.27 5.1 0.024  0.23
Satis_conectividad         0.84      0.84    0.85      0.27 5.3 0.024  0.23
Satis_area_ocio            0.84      0.84    0.85      0.27 5.3 0.024  0.24
Satis_barrio_limp          0.84      0.84    0.85      0.27 5.1 0.023  0.23
Satis_cerca_trab           0.84      0.84    0.85      0.27 5.2 0.024  0.23
Satis_cerca_coleg          0.84      0.84    0.85      0.27 5.2 0.024  0.23
Satis_cerca_comerc         0.84      0.84    0.85      0.27 5.3 0.024  0.24
Satis_cerca_amig_fami      0.85      0.85    0.86      0.28 5.5 0.024  0.24
Satis_tamano_viv           0.84      0.84    0.86      0.27 5.2 0.018  0.24
Satis_calidad_viv          0.84      0.84    0.86      0.27 5.2 0.018  0.24

 Item statistics 
                         r r.cor r.drop
Barrio_ideal          0.70  0.70   0.63
Integra_barrio        0.69  0.69   0.62
Identi_gente          0.67  0.67   0.59
Parte_barrio          0.67  0.67   0.60
Cambio_hogar          0.36  0.27   0.25
Satis_seguridad       0.59  0.55   0.50
Satis_conectividad    0.53  0.47   0.43
Satis_area_ocio       0.53  0.49   0.43
Satis_barrio_limp     0.59  0.56   0.50
Satis_cerca_trab      0.53  0.48   0.44
Satis_cerca_coleg     0.57  0.53   0.48
Satis_cerca_comerc    0.53  0.49   0.44
Satis_cerca_amig_fami 0.44  0.37   0.34
Satis_tamano_viv      0.54  0.45   0.44
Satis_calidad_viv     0.54  0.45   0.44</code></pre>
</div>
</div>
<p>El valor mínimo necesario para considerar que ahí una consistencia interna dentro de un índice/escala es de un alfa de Cronbach superior a 0.60; el valor de consistencia interna de nuestro índice es de un alfa de Cronbach de 0.8471 (0.85 aproximado) según el resultado arrojado por la variable raw_alpha (que sería el alfa de Cronbach).</p>
<p>Aquello indicaría que nuestra escala tiene una alta consistencia interna superando el valor aceptable.</p>
</section>
<section id="confección-de-las-dimensiones-del-índice" class="level3">
<h3 class="anchored" data-anchor-id="confección-de-las-dimensiones-del-índice">4.2 Confección de las dimensiones del índice</h3>
<p>Ya sabiendo que nuestras variables en su conjunto aportarían con la suficiente consistencia interna para la elaboración del índice es que procederíamos a realizarlo.</p>
<p>En primer lugar, lo que habría que hacer corresponde al elaborar las dimensiones con las que se elaboraría dicho índice.</p>
<p>Considerando que el concepto que buscaríamos representar con el índice sería el de “Satisfacción residencial” el cual fue definido tanto en el trabajo anterior (trabajo 1) como en la recapitulación del dicho trabajo en el punto 1.1 es que estableceríamos que el concepto de “Satisfacción residencial” se puede articular a través de 4 dimensiones con la que se conformaría nuestro índice.</p>
<p>Recordando brevemente nuestra definición de “Satisfacción residencial” seria la siguiente: “como una evaluación subjetiva que realiza el individuo sobre sus condiciones de su vivienda y el entorno inmediato en el cual se encuentra, tanto en lo social como en lo físico” (Amérigo, <em>et al</em>, 2014).</p>
<p>A partir de dichas definiciones las dimensiones serían las siguientes:</p>
<p>1 - Identitaria; 2 - Material; 3 - Ambiental y 4 - Ocupacional.</p>
<p>Y cada una representaría lo siguiente:</p>
<p>1 - Identitaria: la evaluación subjetiva que realiza el individuo de su entorno a partir de sus interacciones/relaciones sociales.</p>
<p>2 - Material: la evaluación subjetiva que realiza el individuo sobres las condiciones de su vivienda.</p>
<p>3 - Ambiental: la evaluación subjetiva que realiza el individuo de su entorno inmediato centrándose en aspectos físicos.</p>
<p>4 - Ocupacional: la evaluación subjetiva que realiza el individuo de su entorno inmediato centrándose en aspectos sociales.</p>
<p>La elaboración de esas cuatro dimensiones se realizaría a partir de la siguiente forma:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2 <span class="ot">=</span> proc_data_2022_tr2 <span class="sc">%&gt;%</span> </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Identitaria =</span> <span class="fu">mean</span>(<span class="fu">c</span>(Barrio_ideal, Integra_barrio, Identi_gente, Parte_barrio)),</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Material =</span> <span class="fu">mean</span>(<span class="fu">c</span>(Satis_tamano_viv, Satis_calidad_viv)),</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Ambiental =</span> <span class="fu">mean</span>(<span class="fu">c</span>(Satis_seguridad, Satis_conectividad, Satis_cerca_comerc, Satis_barrio_limp)),</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">Ocupacional =</span> <span class="fu">mean</span>(<span class="fu">c</span>(Satis_cerca_amig_fami, Satis_cerca_trab, Satis_cerca_coleg, Satis_area_ocio))) <span class="sc">%&gt;%</span> </span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Antes de continuar hacemos mención de que la selección de las variables para cada una de las dimensiones se hizo a partir de un criterio de selección donde se relacionó cada una de las variables de la sub-base de datos con la definición que se entregó de cada una de las dimensiones.</p>
<p>Así por ejemplo las variables referidas al barrio se asociaron a la dimensión identitaria; las variables referidas a la satisfacción con la infraestructura/calidad de la vivienda se relacionó con la dimensión material y así respectivamente con las dimensiones restantes.</p>
<p>Respecto a las distribuciones de las variables para la elaboración del índice de “Satisfacción residencial” se emplearon 14 de las 15 variables (no se consideró la variable dependiente de cambio de hogar) y estas se repartieron de la siguiente manera:</p>
<p>1 - Dimensión Identitaria: 4 variables (Barrio_ideal - t02_01; Integra_barrio - t02_02; Identi_gente - t02_03 y Parte_barrio - t02_04).</p>
<p>2 - Dimensión Material: 2 variables (Satis_tamano_viv - t07_01 y Satis_calidad_viv - t07_02).</p>
<p>3 - Dimensión Ambiental: 4 variables (Satis_seguridad - t06_01; Satis_conectividad - t06_02; Satis_cerca_comerc - t06_07 y Satis_barrio_limp - t06_04).</p>
<p>4 - Dimensión Ocupacional: 4 variables (Satis_cerca_amig_fami - t06_08; Satis_cerca_trab - t06_05; Satis_cerca_coleg - t06_06 y Satis_area_ocio - t06_03)</p>
<p>De esta forma intentamos asegurar que la repartición de las variables para cada una de las dimensiones fuese lo más equitativa posible.</p>
</section>
<section id="asignación-de-peso-a-las-dimensiones-y-elaboración-del-índice-de-satisfacción-residencial." class="level3">
<h3 class="anchored" data-anchor-id="asignación-de-peso-a-las-dimensiones-y-elaboración-del-índice-de-satisfacción-residencial.">4.3. Asignación de peso a las dimensiones y elaboración del índice de “Satisfacción residencial”.</h3>
<p>Ya con las dimensiones realizadas procedemos a asignarles peso a cada una de estas; para este caso como son 4 dimensiones y con una distribución de variables relativamente similar le asignamos el mismo peso a cada dimensión el cual sería de 0.25 (25%).</p>
<p>Y habiéndoles asignado un peso a cada una es que realizamos el índice con el siguiente código:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2 <span class="ot">=</span> proc_data_2022_tr2 <span class="sc">%&gt;%</span> </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(Satisfación<span class="at">_residen_pond =</span> (Identitaria<span class="sc">*</span><span class="dv">25</span>) <span class="sc">+</span> (Material<span class="sc">*</span><span class="dv">25</span>) <span class="sc">+</span> (Ambiental<span class="sc">*</span><span class="dv">25</span>) <span class="sc">+</span> (Ocupacional<span class="sc">*</span><span class="dv">25</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Aclaramos que pese a que la dimensión material contaba con solo dos variables le asignamos el mismo peso por fines prácticos y no complejizar el peso correspondiente para cada una de las dimensiones (además si consideramos nuestros antecedentes cada una de las dimensiones que conforma la “Satisfacción residencial” son igual de importantes por lo que no habría ninguna por sobre la otra por lo que se sustentaría nuestra decisión de asignarle el mismo peso).</p>
<p>Además, mencionamos como punto extra que al momento en que cada vez que fuimos creando una dimensión del índice y el posterior índice ya creado se fueron creando variables extras en nuestra sub- base de datos proc_data_2022_tr2 por lo que se pasó de 15 variables a 20 hasta el momento.</p>
</section>
<section id="descriptivos-de-las-dimesiones-y-del-índice-de-satisfacción-residencial" class="level3">
<h3 class="anchored" data-anchor-id="descriptivos-de-las-dimesiones-y-del-índice-de-satisfacción-residencial">4.4. Descriptivos de las dimesiones y del índice de “Satisfacción residencial”</h3>
<p>Descriptivo de la dimensión identitaria:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data_2022_tr2<span class="sc">$</span>Identitaria)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   2.250   3.000   2.693   3.000   4.000     162 </code></pre>
</div>
</div>
<p>Descriptivos de la dimensión material:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data_2022_tr2<span class="sc">$</span>Material)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   3.000   3.000   2.769   3.000   4.000     158 </code></pre>
</div>
</div>
<p>Descriptivo de la dimensión ambiental:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data_2022_tr2<span class="sc">$</span>Ambiental)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   2.000   2.500   2.498   3.000   4.000     165 </code></pre>
</div>
</div>
<p>Descriptivos de la dimensión ocupacional:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data_2022_tr2<span class="sc">$</span>Ocupacional)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   2.250   2.500   2.544   3.000   4.000     204 </code></pre>
</div>
</div>
<p>Descriptivos del indice de “Satisfacción residencial”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data_2022_tr2<span class="sc">$</span>Satisfación_residen_pond)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   12.5   231.2   268.8   262.8   300.0   400.0     213 </code></pre>
</div>
</div>
</section>
<section id="interpretaciones-de-las-dimensiones-de-la-escala-y-del-indice-de-satisfacción-residencial" class="level3">
<h3 class="anchored" data-anchor-id="interpretaciones-de-las-dimensiones-de-la-escala-y-del-indice-de-satisfacción-residencial">4.5. Interpretaciones de las dimensiones de la escala y del indice de “Satisfacción residencial”</h3>
<section id="interpretación-de-las-dimensiones" class="level4">
<h4 class="anchored" data-anchor-id="interpretación-de-las-dimensiones">4.5.1. Interpretación de las dimensiones:</h4>
<p>En primer lugar, podemos observar que cada una de las dimensiones comparten igual valor mínimo y máximo; esto es esperable considerando que cada una de las variables que componen las dimensiones con antelación fueron recodificadas para que sus valores fuesen de 0 a 4.</p>
<p>Lo que resulta interesante de los descriptivos de cada una de las dimensiones seria su media.</p>
<p>La dimensión con la media más baja sería la de la dimensión ambiental con una media de 2.498; mientras que la dimensión con la media más alta sería la de la dimensión material con una media de 2.769.</p>
<p>Las otras dos dimensiones tendrían como valor de sus medias valores intermedios (2.544 para la dimensión ocupacional y 2.693 para la dimensión identitaria).</p>
<p>Lo interesante de aquellos valores es que podemos interpretar que la mayoría de las dimensiones concentran como categorías de respuestas principales las alternativas de “Ni satisfecho ni insatisfecho” y “Satisfecho”.</p>
</section>
<section id="interpretación-del-indice-de-satisfacción-residencial" class="level4">
<h4 class="anchored" data-anchor-id="interpretación-del-indice-de-satisfacción-residencial">4.5.2. Interpretación del indice de “Satisfacción residencial”</h4>
<p>Considerando los valores del índice de “Satisfacción residencial” (la cual se encuentra denominada como Satisfacción_residen_pond) es que sus valores mínimos y máximos son distintos a los de las dimensiones; esto se debería a que para conformar dicho índice; a cada uno de los resultados de las dimensiones se los fue multiplicando por el valor de su peso asignado (el peso asignado fue de 0.25 o del 25% específicamente).</p>
<p>Aun así, su media correspondiente al valor de 262.8 no se diferencia en gran medida de las medias de las otras variables (guardando las proporciones producto al peso asignado a cada dimensión).</p>
<p>Si consideramos el valor mínimo y máximo del índice su media se ubicaría en una posición intermedia de los valores más cercano al valor máximo que a el mínimo (pero aun así distanciándose de los valores mínimos y máximos).</p>
<p>Si consideramos las categorías de respuesta que componen las variables de cada una de las dimensiones que componen el índice y guardo las proporciones en cuanto a las diferencias de valores que tiene cada una de estas podríamos decir que los valores del índice se concentraron en las alternativas de “Ni satisfecho ni insatisfecho” y “Satisfecho”.</p>
<p>Por último, mencionamos un detalle referente al valor mínimo del índice; a diferencia de los valores mínimos de cada una de las dimensiones que compondrían el índice que serían de un valor de 0, el valor mínimo del índice es de 12.5.</p>
<p>Esto creemos que sería debido a que al concentrar todas las categorías de respuestas de la sub-base y de las dimensiones, algunas de esta tuvieron que presentar un valor mínimo distinto a 0 por lo que de ahí se tiene el valor de 12.5; sería difícil que exista alguna observación/caso que tenga valor 0 en cada una de las dimensiones y alternativas de respuesta por lo que sería de esperar que no estuviera el valor mínimo de 0 en el índice.</p>
<p>También influirían el peso de las dimensiones en las puntuaciones como para que el valor mínimo fuese 12.5 y no 0.</p>
<p>Además, podríamos considerar que el valor de 0 en este índice de “Satisfacción residencial” es teóricamente plausible, pero empíricamente difícil.</p>
</section>
</section>
<section id="satisfacción-residencial-general-en-base-a-las-dimensiones" class="level3">
<h3 class="anchored" data-anchor-id="satisfacción-residencial-general-en-base-a-las-dimensiones">4.6. Satisfacción residencial general en base a las dimensiones</h3>
<p>Por último, se podría realizar un paso extra para el análisis; y es que se le puede crear una variable que resuma el nivel de satisfacción residencial que tengan los encuestados a partir de cuan satisfechos estén en diversas dimensiones de lo que compondría el índice de “Satisfacción residencial”.</p>
<p>Para aquello debemos realizar el siguiente código:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>proc_data_2022_tr2 <span class="ot">&lt;-</span> proc_data_2022_tr2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Satisfaccion_reside =</span> <span class="fu">case_when</span>(Satisfación_residen_pond<span class="sc">&gt;=</span><span class="dv">50</span><span class="sc">~</span><span class="st">"Conforme"</span>, Satisfación_residen_pond<span class="sc">&lt;</span><span class="dv">50</span><span class="sc">~</span><span class="st">"No conforme"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El código esta nueva variable denominada como “Satisfaccion_reside” indicaría, si el encuestado estaría satisfecho en por lo menos dos dimensiones del índice de “Satisfacción residencial”.</p>
<p>Realizando una tabla de proporciones y pasándola a porcentajes la distribución de esta variable de “Satisfaccion_reside” estaría distribuida de la siguiente forma:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(proc_data_2022_tr2<span class="sc">$</span>Satisfaccion_reside))<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Conforme No conforme 
 99.8808105   0.1191895 </code></pre>
</div>
</div>
<p>Según la tabla de proporciones se puede concluir que el 99,9% de la muestra que compone la sub-base de datos proc_data_tr2 se encontraría “Conforme” con al menos 2 de las cuatro dimensiones del índice de “Satisfacción residencial”.</p>
<p>El otro 0,1% restante se encontraría “No conforme” con al menos 2 de las cuatro dimensiones del índice de “Satisfacción residencial”.</p>
</section>
</section>
<section id="conclusiones-generales" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones-generales">5. Conclusiones Generales</h2>
<p>Para finalizar considerando lo visto e interpretado a partir de la tabla de correlaciones y del índice de satisfacción residencial” es que podemos concluir que tal parece ser que la “satisfacción residencial” no pareciese ser un elemento que influya mucha en la decisión del cambiarse de hogar de forma preliminar.</p>
<p>La tabla de correlaciones nos indicó que de todas las variables que componen nuestra muestra (sub-base - proc_data_tr2) estas se pueden asociar de diferentes maneras; así analizando la tabla pudimos ver como había variables que tenían correlaciones a simple vista tenían correlaciones muy pequeñas; otras tenían correlaciones pequeñas y otras presentaban correlaciones moderadas y grandes.</p>
<p>Pero aquellas variables como variables independientes eran incapaces de explicar un cambio en nuestra variable dependiente del cambio de hogar.</p>
<p>Con el índice de “Satisfacción residencial” y sus dimensiones elaboradas pudimos ver de la misma forma resultados similares a los de la tabla de correlación; considerando el promedio del índice de sus mediciones; estos presentaban un valor intermedio entre el valor mínimo y el valor máximo por lo que aquello nos indican que gran parte de los encuestados que conforman la muestra se encuentran “Conformes” en al menos dos dimensiones de la “Satisfacción residencial” por lo que aquello presentaría que no hay una relación o asociación clara (o directa) entre la satisfacción residencial y el hecho de querer cambiar de hogar.</p>
<p>Pese a los resultados los cuales de momento no entregarían evidencias suficientes para afirmar o rechazar nuestra hipótesis de investigación (que sería la de que: “a medida que disminuya la satisfacción residencial tanto en sus aspectos físicos y sociales, aumententaria la probabilidad de que el encuestado decida cambiarse de hogar”; este resultado no sería negativo del todo para la investigación.</p>
<p>Como se dijo anteriormente todavía no se cuenta con evidencia suficiente como para aceptar y/o rechazar la hipótesis de investigación; además el índice si aportaría a uno de los objetivos de la investigación, el cual sería el determinar dimensión (o determinante según los criterios del trabajo 1) sería la más determinante al momento de entender el concepto de “Satisfacción residencial”.</p>
<p>Esta sería la dimensión (o determinante) de Material con una media de 2.769 la más alta de las 4 dimensiones (que serían: la Identitaria; Material; Ambiental y la ocupacional.</p>
<section id="conclusiones-respecto-a-las-limitaciones-de-este-trabajo" class="level3">
<h3 class="anchored" data-anchor-id="conclusiones-respecto-a-las-limitaciones-de-este-trabajo">5.1. Conclusiones respecto a las limitaciones de este trabajo</h3>
<p>Consideramos que igualmente parte de las conclusiones realizadas en el punto anterior esta sujetas en parte a las limitaciones de este trabajo; al ser este un trabajo de carácter transversal está sujeto a un momento determinado del tiempo (que en este caso sería el año 2022) por lo que de ahí es posible que se pueda entender lo limitada que pareciese los resultados obtenidos.</p>
<p>También creemos que podría ser considerado como un limitante las variables que empleamos para este trabajo; las cuales pese a ser las idóneas bajo nuestros criterios para representar por ejemplo la definición y dimensiones que nosotros mismos establecimos de la “Satisfacción residencial” carecemos de variables con las cuales se puede caracterizar al encuestado (como lo seria por ejemplo de que región es; sexo; edad o educación) y aquellas variables podría ayudar a describir o articular de mejor manera el fenómeno que buscamos investigar además de complementarla.</p>
</section>
<section id="consideraciones-a-futuro" class="level3">
<h3 class="anchored" data-anchor-id="consideraciones-a-futuro">5.2. Consideraciones a futuro</h3>
<p>Por lo que consideraríamos a futuro el quizás agregar más variables con información sociodemográfica para caracterizar mejor a los encuestados y relacionar de manera más precisa al fenómeno que buscamos investigar y también así poder contar con más información como para poder afirmar o rechazar nuestra hipótesis de investigación.</p>
<p>También no descartamos la posibilidad de utilizar otros modelos analíticos para poder hallar una respuesta a nuestra hipótesis de investigación y poder sortear las limitaciones de este trabajo; por ejemplo, no descartaríamos la posibilidad de utilizar modelos de regresión simples y múltiples.</p>
<p>También no descartamos la posibilidad de aprovechar el hecho de que al ser la encuesta del ELSOC una encuesta longitudinal el comparar la información de este año (2022) con la de otros años para así poder sortear una de las principales limitantes de este trabajo el cual sería el de ser un estudio transversal sujeto a un determinado momento del tiempo y además así también; poder sumar información que permita poder dar cuenta de cambios que nos permitan afirmar o rechazar nuestra hipótesis de investigación y el poder así también responder los objetivos de esta investigación.</p>
</section>
</section>
<section id="bibliografia-1" class="level2">
<h2 class="anchored" data-anchor-id="bibliografia-1">6. Bibliografia</h2>
<p>La bibliografía mencionada en este trabajo corresponde al siguiente texto:</p>
<p>Amérigo, M., &amp; Aragonés, J. I. (1988). Satisfacción residencial en un barrio remodelado: Predictores físicos y sociales. International Journal of Social Psychology, 3(1), 61–70. <a href="https://doi.org/10.1080/02134748.1988.10821574" class="uri">https://doi.org/10.1080/02134748.1988.10821574</a></p>
<p>Debido a que seguimos presentando problemas con el software de Zotero no pudimos poner la bibliografía como corresponde.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>